language: node_js
node_js:
- 6 
addons:
  apt:
    packages:
       libaio1
       build-essential
       curl
       unzip
before_install:
- source /home/travis/build/jerrythomas/curious-api/scripts/node_oracle_env.sh
notifications:
  email: false
