language: node_js
node_js:
- "stable"
addons:
  apt:
    packages:
       libaio1
       build-essential
       curl
       unzip
  sonarcloud:
    organization: "jerrythomas-github"
    branches :
      - sonarqube

jdk:
  - oraclejdk8

script:
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'    
before_install:
  - source ./scripts/node_oracle_env.sh
env:
  - PORT=8000
  - BASE_URL=http://localhost:8000
  - PACKAGE_VERSION="0.0.*"
after_success:
- npm run coveralls
notifications:
  email: false
